version: '3.4'

volumes:
  gem_path:

services:
  jekyll:
    image: jekyll/jekyll:stable
    container_name: jekyll_jazzbba
    volumes:
      - ./docs:/srv/jekyll/site
      - ./_site:/srv/jekyll/_site
      - gem_path:/usr/gem
    ports:
      - "80:4000"
    command: jekyll serve --source site
